Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -24,9 +24,16 @@ jobs:
         sudo apt update
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        if [ -f requirements.txt ]; then python3 -m pip install --upgrade pip -r requirements.txt; fi
+        if [ -f requirements.txt ]; then
+        if command -v python3 &>/dev/null; then
+            python3 -m pip install --upgrade pip -r requirements.txt
+        elif command -v pip3 &>/dev/null; then
+            pip3 install --upgrade pip -r requirements.txt
+        else
+            echo "Unable to find Python or pip executable."
+            exit 1
+        fi
+        
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
